Reduce dependency on Boost.TypeTraits now that C++ >= 11 is required.
This allows to workaround the following error when using clang >= 21 on
the following code:

    #include <string>
    #include <iostream>
    #include "boost/lexical_cast.hpp"

    enum SomeEnum
    {
        OneValue
    };

    int main()
    {
        std::cout << boost::lexical_cast<std::string>(SomeEnum::OneValue) << std::endl;
    }

    /app/boost/include/boost/type_traits/is_signed.hpp:37:25: error: in-class initializer for static data member is not a constant expression
       37 |    static const no_cv_t minus_one = (static_cast<no_cv_t>(-1));

    ... (snapped)

    /app/boost/include/boost/type_traits/is_signed.hpp:37:38: note: integer value -1 is outside the valid range of values [0, 1] for the enumeration type 'SomeEnum'
       37 |    static const no_cv_t minus_one = (static_cast<no_cv_t>(-1));